version: '3.9'

services:

  transaction_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres123!"
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
